spring:
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: shop
  log:
    file-path: /log/shop
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver # 사용하는 DB 드라이버
    url: jdbc:mariadb://localhost:3306/shop
#    url: jdbc:mariadb://192.168.219.10:3306/delivery?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: shopuser
    password: 123456

    jpa:
      hibernate:
        # none: 아무것도 하지 않음 (운영 환경 권장)
        # update: 변경된 부분만 반영
        # create: 매번 테이블 새로 생성
        ddl-auto: none

      show-sql: true # 콘솔에 SQL 출력
      properties:
        hibernate:
          format_sql: true # SQL을 보기 좋게 정렬
          highlight_sql: true # SQL 키워드 색상 표시 (선택사항)
          default_batch_fetch_size: 100 # 성능 최적화를 위한 배치 사이즈

      # 데이터베이스 방언 설정 (DB 종류에 맞게 SQL 최적화)
      database-platform: org.hibernate.dialect.MariaDB106Dialect
      logging:
        level:
          org.hibernate.SQL: debug         # 실행되는 SQL 출력
          org.hibernate.orm.jdbc.bind: trace # (중요) SQL에 들어가는 파라미터 값(? 표시) 출력
  # mybatis 용
#  datasource:
#    hikari:
#      max-lifetime: 1680000
server:
  port: 8081  # 기본 포트(8080) 외에 8081, 9000 등 원하는 번호로 변경 가능
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

shop:
  password-key: c87bbfdef386f15d0b2003e061f9c058a70ff2d1
  jwt-key: aebb238c463a1f4faf4db901bfab2445d75a7aa68bd930fdb7ecb95081b36fc6